name: 'Deploy to firebase hosting'
description: 'Deploy to firebase hosting with npm cache'
inputs:
  projectId:
    description: 'Firebase project ID'
    required: true
  serviceAccount:
    description: 'Firebase service account'
    required: true
  GITHUB_TOKEN:
    description: 'secrets.GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    # Used by FirebaseExtended/action-hosting-deploy which use npx
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: '.github/workflows/*.yml'
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ inputs.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ inputs.serviceAccount }}'
        channelId: live
        projectId: '${{ inputs.projectId }}'
